[[item]]
title = "Tuulinuolet"
layer = "fmi:ecmwf:arrows:wind"

[[item]]
title = "Pilven pohjat"
layer = "fmi:ecmwf:cloudbase2"

[[item]]
title = "Keskilämpötila 1d"
layer = "fmi:ecmwf:dailymeantemprature"

[[item]]
title = "Sateen olomuoto"
layer = "fmi:ecmwf:europe:precipitationform"

[[item]]
title = "Tuuli (puuskat)"
layer = "fmi:ecmwf:windgust"

[[item]]
title = "Max lämpötila 06"
layer = "fmi:ecmwf:finland:maximumtemperature06"

[[item]]
title = "Min lämpötila 06"
layer = "fmi:ecmwf:finland:minimumtemperature06"

[[item]]
title = "Ilmankosteus"
layer = "fmi:ecmwf:humidity"

[[item]]
title = "Ilmankosteus"
layer = "fmi:ecmwf:humidity"
