[[item]]

title = "Pilvisyys"
description = "Pilvisyysennuste"
layer = "Weather:cloudiness-forecast"

[[item]]

title = "Lämpötilaennuste (Hirlam)"
description = "Lämpötilaennuste (Hirlam)"
layer = "Weather:temperature-forecast"

