[[item]]
title = "Tuulen nopeus"
layer = "fmi:harmonie:windspeedms"

[[item]]
title = "Näkyvyys"
layer = "fmi:harmonie:visibility"

[[item]]
title = "Lämpötila"
layer = "fmi:harmonie:temperature"

[[item]]
title = "Ilmankosteus"
layer = "fmi:harmonie:humidity"
