# Main menu configuration

[[metadata]]

name = "fmiwms"
type = "GetCapabilities"
url = "http://wms.fmi.fi/fmi-apikey/{APIKEY}/geoserver/wms?request=GetCapabilities&service=WMS"

[[menu]]

title = "Tutka"
type = "obs"
file = "radar.toml"

[[menu]]

title = "Satelliitti"
type = "obs"
file = "satellite.toml"

[[menu]]

title = "Ennusteet"
type = "for"
file = "forecasts.toml"
