# Main menu configuration
[[source]]
name = "fmiopenwms"
type = "wms"
url = "https://openwms.fmi.fi/geoserver/"
tileCapabilities = "https://openwms.fmi.fi/geoserver/gwc/service/wmts?request=GetCapabilities"
timeCapabilities = "https://openwms.fmi.fi/geoserver/wms?request=GetCapabilities&service=WMS"
default = true
server = "geoserver"

[[source]]
name = "ecmwf"
type = "wms"
url = "https://apps.ecmwf.int/wms/"
tileCapabilities = "https://apps.ecmwf.int/wms/?token=public&request=GetCapabilities&service=WMS"
timeCapabilities = "https://apps.ecmwf.int/wms/?token=public&request=GetCapabilities&service=WMS"
server = "geoserver"

[[menu]]
title = "Tutka"
type = "obs"
file = "radar.toml"

[[menu]]
title = "Satelliitti"
type = "obs"
file = "satellite.toml"

[[menu]]
title = "Ennusteet"
type = "for"
file = "forecasts.toml"

[[menu]]
title = "J채채kartta"
type = "obs"
file = "icecoverage.toml"

[[menu]]
title = "ECMWF"
file = "ecmwf.toml"

[[menu]]
title = "PAL"
file = "pal.toml"

[[menu]]
title = "PAL testieditointi"
file = "pal_test.toml"

[[menu]]
title = "Helmi"
file = "helmi.toml"

[[menu]]
title = "HBM"
file = "hbm.toml"

[[menu]]
title = "Ties채채"
file = "tiesaa.toml"

[[menu]]
title = "MST"
file = "mst.toml"

[[menu]]
title = "Harmonie"
file = "harmonie.toml"
