# Main menu configuration
[[source]]
name = "fmiopenwms"
type = "wms"
url = "https://openwms.fmi.fi/geoserver/"
tileCapabilities = "https://openwms.fmi.fi/geoserver/gwc/service/wmts?request=GetCapabilities"
timeCapabilities = "https://openwms.fmi.fi/geoserver/wms?request=GetCapabilities&service=WMS"
default = true
server = "geoserver"

[[source]]
name = "ecmwf"
type = "wms"
url = "https://apps.ecmwf.int/wms/"
tileCapabilities = "https://apps.ecmwf.int/wms/?token=public&request=GetCapabilities&service=WMS"
timeCapabilities = "https://apps.ecmwf.int/wms/?token=public&request=GetCapabilities&service=WMS"
server = "geoserver"
