[[item]]

title = "Tutka rr1h Suomi"
description = "The best rr1h radar layer for Finland"
layer = "Radar:suomi_rr1h_eureffin"

[[item]]

title = "Tutka precipitationrate (rr) Suomi"
layer = "Radar:suomi_rr_eureffin"

[[item]]
title =  "Tuliset precipitationrate (rr) Suomi"
layer = "fmi:tuliset:precipitationrate"
type = "for"
source = "fmidaliwms"
