[[item]]
title = "Destia - Tien lämpötila"
layer = "fmi:tiesaa-destia:roadtemperature"

[[item]]
title = "Tien tila"
layer = "fmi:tiesaa:roadcondition"

[[item]]
title = "Tie notifikaatiot"
layer = "fmi:tiesaa:roadnotification"

[[item]]
title = "Tie varoitukset"
layer = "fmi:tiesaa:roadwarning"